# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('startingDate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pathOrigin', models.CharField(max_length=200)),
                ('pathConverted', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('uploadDate', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Competition')),
            ],
        ),
    ]
