# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_competition_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pathConverted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pathOrigin',
        ),
        migrations.AddField(
            model_name='video',
            name='converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='convertido',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AddField(
            model_name='video',
            name='original_video',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
