# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160830_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='convertido',
            new_name='converted_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='converted',
        ),
    ]
