# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160831_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='video',
            name='uploadDate',
            field=models.DateTimeField(null=True),
        ),
    ]
