# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160902_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user_email',
            field=models.CharField(max_length=60),
        ),
    ]
