# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160903_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(null=True, upload_to='upload_files/competitions/images'),
        ),
    ]
