# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_merge_20160903_1820'),
        ('web', '0015_merge_20160903_1430'),
    ]

    operations = [
    ]
