# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_merge_20160903_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='converted_video',
            field=models.FileField(blank=True, null=True, upload_to='static/upload_files/competitions/videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_video',
            field=models.FileField(null=True, upload_to='static/upload_files/competitions/videos'),
        ),
    ]
