# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20160903_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
