# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_merge_20160903_2226'),
        ('web', '0018_auto_20160903_1843'),
    ]

    operations = [
    ]
