# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_merge_20160904_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='converted_video',
            field=models.FileField(null=True, upload_to='static/upload_files/competitions/videos'),
        ),
    ]
